### ISSUE TITLE
Master Front Page Redesign Items

### ISSUE THREAD

**Issue by ArendPeter** [Equal-Vote/star-server#547]
We have a lot of tasks related to the front page. The future of the front page is still unclear so I'm collecting all the tasks here for consideration

- [x] Add user's name to navbar https://github.com/Equal-Vote/star-server/issues/526
- [x] Carousel https://github.com/Equal-Vote/star-server/issues/431
- [x] Mickael's Design https://starvoting.slack.com/archives/C01EBAT283H/p1710603768761129
- [x] Do we even want quick poll on the front page? #496 
- [x] Fix quick poll labels https://github.com/Equal-Vote/star-server/issues/280 (Mike may have fixed this in a separate branch)
- [x] Sara's proposal https://starvoting.slack.com/archives/G015A50PK6W/p1710128638965009
- [x] Include equal vote logo in the footer
- [x] Add learn more / better voting to the header
- [x] Make the non-hero section look pretty
- [x] Update footer with copyright from Sara's example
